package com.lacoste.verification;
import android.Manifest;import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import com.google.firebase.messaging.FirebaseMessaging;
public class MainActivity extends Activity { @Override protected void onCreate(Bundle b){super.onCreate(b);ui();} LinearLayout root; TextView status; EditText key; int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} TextView tv(String x){TextView t=new TextView(this);t.setText(x);t.setTextSize(15);t.setPadding(0,dp(8),0,dp(8));return t;} void ui(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(25),dp(18),dp(25));root.addView(tv("LC VERIFICATION"));root.addView(tv("Verificação de pagamentos por SMS"));root.addView(tv("Device ID: "+VerificationStore.deviceId(this)));status=tv("Estado: a verificar...");root.addView(status);key=new EditText(this);key.setHint("Chave de licença");root.addView(key);Button b=new Button(this);b.setText("Ativar / verificar licença");root.addView(b);Button sms=new Button(this);sms.setText("Permitir SMS e notificações");root.addView(sms);Button notif=new Button(this);notif.setText("Abrir acesso às notificações");root.addView(notif);Button ver=new Button(this);ver.setText("Ver últimos SMS recebidos");root.addView(ver);b.setOnClickListener(v->ativar());sms.setOnClickListener(v->pedir());ver.setOnClickListener(v->mostrarSms());notif.setOnClickListener(v->{try{startActivity(new Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS"));}catch(Exception ignored){}});setContentView(root);pedir();verificar();}
 void pedir(){if(Build.VERSION.SDK_INT>=23)requestPermissions(new String[]{Manifest.permission.RECEIVE_SMS,Manifest.permission.READ_SMS,Manifest.permission.POST_NOTIFICATIONS},44);}
 void ativar(){String k=key.getText().toString().trim();if(k.isEmpty()){status.setText("Estado: introduz a chave.");return;}status.setText("Estado: a enviar pedido...");new Thread(()->{try{org.json.JSONObject r=VerificationApi.requestLicense(this,k);if(r.optBoolean("ok")){VerificationStore.setLicense(this,k);VerificationStore.setRequestId(this,r.optString("requestId"));if("approved".equals(r.optString("status"))){VerificationStore.setToken(this,r.optString("deviceToken"));VerificationStore.setExpires(this,r.optString("expiresAt"));}runOnUiThread(()->status.setText("Estado: "+r.optString("status")));}else runOnUiThread(()->status.setText("Erro: "+r.optString("message")));}catch(Exception e){runOnUiThread(()->status.setText("Erro: "+e.getMessage()));}}).start();}
 void verificar(){FirebaseConfig.init(this);try{FirebaseMessaging.getInstance().getToken().addOnSuccessListener(t->new Thread(()->{try{VerificationApi.register(this,t);}catch(Exception ignored){}}).start());}catch(Exception ignored){}new Thread(()->{try{org.json.JSONObject r=VerificationApi.status(this);if("approved".equals(r.optString("status"))){VerificationStore.setToken(this,r.optString("deviceToken",VerificationStore.token(this)));VerificationStore.setExpires(this,r.optString("expiresAt"));}runOnUiThread(()->status.setText("Estado: "+r.optString("status")));}catch(Exception e){runOnUiThread(()->status.setText("Estado: servidor indisponível"));}}).start();}
 void mostrarSms(){ try{ if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.READ_SMS)!=0){pedir();return;} android.database.Cursor c=getContentResolver().query(android.net.Uri.parse("content://sms/inbox"),new String[]{"address","body","date"},null,null,"date DESC LIMIT 10");StringBuilder x=new StringBuilder("ÚLTIMOS SMS\n\n");if(c!=null){while(c.moveToNext()){x.append(c.getString(0)).append("\n").append(c.getString(1)).append("\n\n");}c.close();}new AlertDialog.Builder(this).setTitle("SMS recebidos").setMessage(x.toString()).setPositiveButton("Fechar",null).show();}catch(Exception e){Toast.makeText(this,"Não foi possível ler os SMS: "+e.getMessage(),Toast.LENGTH_LONG).show();}}

}
