package com.lacoste.verification;
import android.content.*;import android.os.Build;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import org.json.*;
public final class VerificationApi { private static final String BASE="https://lacoste-site.vercel.app"; private VerificationApi(){}
 static JSONObject req(String path,String method,JSONObject body,String token)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(BASE+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(12000);c.setReadTimeout(12000);c.setRequestProperty("Content-Type","application/json");if(token!=null&&!token.isEmpty())c.setRequestProperty("X-App-Token",token);if(body!=null){c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}}InputStream in=c.getResponseCode()>=400?c.getErrorStream():c.getInputStream();if(in==null)return null;BufferedReader r=new BufferedReader(new InputStreamReader(in));StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);c.disconnect();return new JSONObject(s.toString());}
 public static JSONObject requestLicense(Context c,String key)throws Exception{JSONObject b=new JSONObject();b.put("licenseKey",key.toUpperCase());b.put("androidId",VerificationStore.deviceId(c));b.put("model",Build.MANUFACTURER+" "+Build.MODEL);b.put("deviceRole","verification");b.put("platform","android");return req("/api/licenca/request","POST",b,null);}
 public static JSONObject status(Context c)throws Exception{return req("/api/licenca/status?androidId="+URLEncoder.encode(VerificationStore.deviceId(c),"UTF-8")+"&requestId="+URLEncoder.encode(VerificationStore.requestId(c),"UTF-8"),"GET",null,null);}
 public static JSONObject register(Context c,String fcm)throws Exception{JSONObject b=new JSONObject();b.put("deviceId",VerificationStore.deviceId(c));b.put("androidId",VerificationStore.deviceId(c));b.put("fcmToken",fcm);b.put("deviceRole","verification");return req("/api/autosistema/verificacao/registar","POST",b,VerificationStore.token(c));}
 public static JSONObject verify(Context c,String pedidoId,String paymentId)throws Exception{JSONObject b=new JSONObject();b.put("deviceId",VerificationStore.deviceId(c));b.put("pedidoId",pedidoId);b.put("paymentId",paymentId);return req("/api/autosistema/verificacao/pagamento","POST",b,VerificationStore.token(c));}
}
