org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=false

FIREBASE_API_KEY=AIzaSyD-IAivEoY9bFLv9kS1xCz7NORYWjUweyU
FIREBASE_APP_ID=1:417979947808:android:9178109ced005284555545
FIREBASE_PROJECT_ID=lacoste-auto
FIREBASE_MESSAGING_SENDER_ID=417979947808
